package com.railflow.yardops.api;
import com.railflow.yardops.domain.*; import com.railflow.yardops.repository.*; import com.railflow.yardops.service.EventIngestionService; import org.springframework.http.HttpStatus; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api") @CrossOrigin(origins="*") public class ApiController {
 private final ShipmentRepository shipments; private final RailcarRepository railcars; private final TrainRepository trains; private final YardRepository yards; private final AlertRepository alerts; private final ScanEventRepository events; private final RouteSegmentRepository segments; private final EventIngestionService ingestion;
 public ApiController(ShipmentRepository shipments,RailcarRepository railcars,TrainRepository trains,YardRepository yards,AlertRepository alerts,ScanEventRepository events,RouteSegmentRepository segments,EventIngestionService ingestion){this.shipments=shipments;this.railcars=railcars;this.trains=trains;this.yards=yards;this.alerts=alerts;this.events=events;this.segments=segments;this.ingestion=ingestion;}
 @GetMapping("/shipments") public List<Shipment> shipments(@RequestParam(required=false) ShipmentStatus status){return status==null?shipments.findAll():shipments.findByStatus(status);} @GetMapping("/shipments/{id}") public Shipment shipment(@PathVariable UUID id){return shipmentOrThrow(id);} @PostMapping("/shipments") public Shipment createShipment(@RequestBody ShipmentRequest r){return shipments.save(new Shipment(r.reference(),r.origin(),r.destination(),r.commodity(),r.customer(),r.priority()));} @PatchMapping("/shipments/{id}/status") public Shipment updateStatus(@PathVariable UUID id,@RequestBody StatusRequest r){Shipment s=shipmentOrThrow(id);s.setStatus(r.status());return shipments.save(s);} @PostMapping("/shipments/{id}/railcars/{carNumber}") public Shipment assignRailcar(@PathVariable UUID id,@PathVariable String carNumber){railcars.findByCarNumber(carNumber).orElseThrow(()->notFound("Railcar"));Shipment s=shipmentOrThrow(id);s.assignRailcar(carNumber);return shipments.save(s);}
 @GetMapping("/railcars") public List<Railcar> railcars(@RequestParam(required=false) String location,@RequestParam(required=false) RailcarStatus status){List<Railcar> result=railcars.findAll();if(location!=null)result=result.stream().filter(c->location.equalsIgnoreCase(c.getLocation())).toList();if(status!=null)result=result.stream().filter(c->status==c.getStatus()).toList();return result;} @PostMapping("/railcars") public Railcar createRailcar(@RequestBody RailcarRequest r){return railcars.save(new Railcar(r.carNumber(),r.type(),r.capacity(),r.location(),r.commodity(),r.status()==null?RailcarStatus.AVAILABLE:r.status()));} @GetMapping("/railcars/{carNumber}/events") public List<ScanEvent> railcarEvents(@PathVariable String carNumber){return events.findByCarNumberOrderByOccurredAtDesc(carNumber);}
 @GetMapping("/trains") public List<Train> trains(){return trains.findAll();} @PostMapping("/trains") public Train createTrain(@RequestBody TrainRequest r){return trains.save(new Train(r.trainNumber(),r.origin(),r.destination(),r.departureAt(),r.arrivalAt(),r.status()));} @GetMapping("/trains/{trainNumber}/segments") public List<RouteSegment> segments(@PathVariable String trainNumber){return segments.findByTrainNumber(trainNumber);} @PostMapping("/trains/{trainNumber}/segments") public RouteSegment createSegment(@PathVariable String trainNumber,@RequestBody SegmentRequest r){return segments.save(new RouteSegment(trainNumber,r.originYard(),r.destinationYard(),r.scheduledDeparture(),r.scheduledArrival(),"SCHEDULED"));}
 @PostMapping("/trains/{trainNumber}/railcars/{carNumber}") public Train assignTrainRailcar(@PathVariable String trainNumber,@PathVariable String carNumber){Train train=trains.findAll().stream().filter(t->trainNumber.equals(t.getTrainNumber())).findFirst().orElseThrow(()->notFound("Train"));railcars.findByCarNumber(carNumber).orElseThrow(()->notFound("Railcar"));train.assignRailcar(carNumber);return trains.save(train);} 
 @GetMapping("/yards") public List<Yard> yards(){return yards.findAll();} @PostMapping("/yards") public Yard createYard(@RequestBody YardRequest r){return yards.save(new Yard(r.code(),r.name(),r.city(),r.trackCapacity(),r.occupiedTracks()));} @GetMapping("/yards/{code}/events") public List<ScanEvent> yardEvents(@PathVariable String code){return events.findByYardCodeOrderByOccurredAtDesc(code);} @GetMapping("/yards/{code}/switch-list") public List<Map<String,String>> switchList(@PathVariable String code){return railcars.findAll().stream().filter(car->code.equalsIgnoreCase(car.getLocation())).map(car->Map.of("carNumber",car.getCarNumber(),"action","SPOT","track",code,"commodity",String.valueOf(car.getCommodity()))).toList();}
 @GetMapping("/alerts") public List<OperationalAlert> alerts(@RequestParam(required=false) AlertSeverity severity,@RequestParam(required=false) AlertStatus status){List<OperationalAlert> result=alerts.findAll();if(severity!=null)result=result.stream().filter(a->severity==a.getSeverity()).toList();if(status!=null)result=result.stream().filter(a->status==a.getStatus()).toList();return result;} @PatchMapping("/alerts/{id}/acknowledge") public OperationalAlert acknowledge(@PathVariable UUID id){OperationalAlert a=alertOrThrow(id);a.acknowledge();return alerts.save(a);} @PatchMapping("/alerts/{id}/resolve") public OperationalAlert resolve(@PathVariable UUID id){OperationalAlert a=alertOrThrow(id);a.resolve();return alerts.save(a);}
 @PostMapping("/events") public ScanEvent event(@RequestBody ScanRequest r){return ingestion.ingest(new ScanEvent(r.carNumber(),r.yardCode(),r.eventType(),r.occurredAt()==null?Instant.now():r.occurredAt()));} @GetMapping("/dashboards/operations") public Map<String,Object> dashboard(){return Map.of("activeShipments",shipments.count(),"trainsInTransit",trains.count(),"yards",yards.findAll(),"openAlerts",alerts.countByStatus(AlertStatus.OPEN),"serviceStatus","operational");}
 private Shipment shipmentOrThrow(UUID id){return shipments.findById(id).orElseThrow(()->notFound("Shipment"));} private OperationalAlert alertOrThrow(UUID id){return alerts.findById(id).orElseThrow(()->notFound("Alert"));} private ResponseStatusException notFound(String name){return new ResponseStatusException(HttpStatus.NOT_FOUND,name+" not found");}
 public record ShipmentRequest(String reference,String origin,String destination,String commodity,String customer,String priority){} public record StatusRequest(ShipmentStatus status){} public record RailcarRequest(String carNumber,String type,Integer capacity,String location,String commodity,RailcarStatus status){} public record TrainRequest(String trainNumber,String origin,String destination,Instant departureAt,Instant arrivalAt,String status){} public record YardRequest(String code,String name,String city,Integer trackCapacity,Integer occupiedTracks){} public record SegmentRequest(String originYard,String destinationYard,Instant scheduledDeparture,Instant scheduledArrival){} public record ScanRequest(String carNumber,String yardCode,String eventType,Instant occurredAt){}
}